### ISSUE TITLE
Dealing with only specific atom environments 

### ISSUE THREAD

**Issue by sandipde** [lab-cosmo/chemiscope#134] opened 2021-05-28 16:06 UTC
At the moment, there is a hard restriction on the way the environment centric viewer can be activated. The data for all the all the atoms in the structure has be supplied. In practice, it is often the case that I want to build the map focussing on only specific atoms of interest (eg. Cu atoms in a Zeolite). It would be great to 
1. either remove the restriction by only checking consistency on the number of descriptors and the env prop 
2. Allowing "None" values  in the descriptors and properties for the environments of not interest. I believe Plotly can handle None values by hiding them. In your library however you are checking for string/float and hence my attempt to pass None failed.

**Comment by Luthaf** [comment] 2021-05-28 20:21
> either remove the restriction by only checking consistency on the number of descriptors and the env prop

This is a duplicate of #38, but with a better explanation of the problem, so I'll close #38 in favor of this one.

> Allowing "None" values in the descriptors and properties for the environments of not interest. I believe Plotly can handle 
None values by hiding them. In your library however you are checking for string/float and hence my attempt to pass None failed.

The trick we have been using is to set properties for the environments we don't want to show on the map to NaN, and this causes plotly to hide them. 

I don't know how the plotly python bindings deal with None, since there is no such thing in Javascript. Maybe None values are mapped to `null`, and plotly hide these? I'll try to look into this.

**Comment by Luthaf** [comment] 2021-05-28 20:22
To be clear, even if the NaN trick should work fine we still want to support this use case natively, if nothing else to reduce the size of the JSON files.

**Comment by sandipde** [comment] 2021-05-28 22:19
Thanks @Luthaf for the prompt response. I did not check np.NaN option but if that works then that's a equivalent work around of the None option (yes in js it would be null). As you correctly said it would be indeed great to have native support for this.

**Comment by Luthaf** [comment] 2022-01-24 14:05
Fixed by #166! 

Here is a script one can use to convert from the "old" NaN based representation of sparse environment list to the new format: https://gist.github.com/Luthaf/489599acbc1633451ca59838a55dd1a0

**Closed by Luthaf** 2022-01-24 14:05 UTC
Labels: enhancement
