### ISSUE TITLE
Periodic neighbors of molecules are shown

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/chemiscope#331] opened 2024-04-17 13:07 UTC
I want to verify a dataset with my favorite visualization tool, but I obtain confusing view.

I have a test structure with one single water molecule but chemiscope is showing me my molecule plus 3 "ghost" atoms. 

![chemiscope-structure](https://github.com/lab-cosmo/chemiscope/assets/15192133/ac2673bf-0d0f-41cf-a2b0-c5d9a6d94a82)
[h2o_mic.xyz.txt](https://github.com/lab-cosmo/chemiscope/files/15011264/h2o_mic.xyz.txt)

 I already talked to @Luthaf and I know that this is intended behavior and makes looking and crystals much nicer.

But, for molecules it can be very confusing - at least it is for me. I know that I can get rid of it if I move my atoms away from the origin or disable the PBC but this is not really useful if one wants to verify something and it is required to first manipulate them. 

I rather would have a bool viewer option like there is already one for `cell` etc or an addition to the already existing option to show the neighboring cells.

**Comment by PicoCentauri** [comment] 2024-04-17 13:23
I think showing the cell is useful. I have a dataset where I scale the cell but the positions of my atoms are the same between the structures. Verifying, that I actually scaled the cell correctly only works when I see the cell and my atoms.

**Comment by ceriottm** [comment] 2024-04-18 06:44
Has this always been enabled? I remember one had to manually select replicas to see entire molecules that are broken across the periodic boundaries. I also find this behavior confusing, TBH.

**Comment by Luthaf** [comment] 2024-04-23 10:27
This was actually not the intended behavior (I got a bit confused) but a change inside 3Dmol. Should be fixed by #332

**Closed** 2024-04-23 20:53 UTC
Labels: component-structure
