### ISSUE TITLE
Freezing upon settings change

### ISSUE THREAD

**Issue by cbefan** [lab-cosmo/chemiscope#328] opened 2024-02-21 23:17 UTC
Switching to 2d plot freezes interface. Others not experiencing this issue with the same input file. See attached video.

OS: Windows 11
Browser: Microsoft Edge (and Google Chrome)
[broken chemiscope.zip](https://github.com/lab-cosmo/chemiscope/files/14366124/broken.chemiscope.zip)

@rosecers 
@Luthaf , any suggestions as to what is causing this?

**Comment by ceriottm** [comment] 2024-02-22 08:19
I'd be tempted to blame Edge but I see you mention this also happens with Chrome.... 
Looks like a browser issue though, maybe switching from different graphics modes in plotly?
Maybe try to share the chemiscope json and we can test it to see if we can reproduce.

**Comment by Luthaf** [comment] 2024-02-29 13:19
> any suggestions as to what is causing this?

Without being able to reproduce, I have no idea what's happening. To be able to help I'll need some input file that reliably reproduces the issue (i.e. does not only fail on your own computer). Otherwise it might just be an issue somewhere with your OS/Browser settings.

**Comment by ceriottm** [comment] 2024-03-21 08:31
Closing this as not reproducible.

**Closed by ceriottm** 2024-03-21 08:31 UTC
